---
deployment:
  tasks:
    - /bin/bash -lc '
        set -euo pipefail
        DEPLOYPATH="/home/drrootsdc/betaroot1"   # change to /home/drrootsdc/public_html/betaroot if that is your web path
        SOURCE="/home/drrootsdc/repositories/betaroot"
        LOG="/home/drrootsdc/deploy.log"

        {
          echo "===== FIX v2 $(date) ====="
          echo "SRC: $SOURCE"
          echo "DST: $DEPLOYPATH"

          # Ensure destination exists and is writable
          mkdir -p "$DEPLOYPATH"
          chmod -R u+rwX "$DEPLOYPATH" || true

          # Never keep a .git inside the live folder
          if [ -d "$DEPLOYPATH/.git" ]; then
            echo "Removing stray .git in destination"
            rm -rf "$DEPLOYPATH/.git"
          fi

          # Use rsync if present (wherever it is), else tar fallback that excludes .git and .cpanel.yml
          RSYNC="$(command -v rsync || true)"
          if [ -n "$RSYNC" ]; then
            echo "Using rsync at: $RSYNC"
            "$RSYNC" -a --delete \
              --exclude ".git" \
              --exclude ".cpanel.yml" \
              "$SOURCE"/ "$DEPLOYPATH"/
          else
            echo "rsync not found; using tar fallback"
            # Wipe current contents (safe sync)
            find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
            # Copy everything except .git and .cpanel.yml
            ( cd "$SOURCE" && tar --exclude=.git --exclude=.cpanel.yml -cf - . ) | ( cd "$DEPLOYPATH" && tar -xf - )
          fi

          echo "Done: $(date)"
        } >> "$LOG" 2>&1
      '
