---
deployment:
  tasks:
    - export DEPLOYPATH=/home/drrootsdc/betaroot
    - echo "Deploy to $DEPLOYPATH at $(date)" >> /home/drrootsdc/deploy.log
    - /usr/bin/rsync -a --delete \
        --exclude ".git" \
        --exclude ".cpanel.yml" \
        ./ "$DEPLOYPATH"/
