---
deployment:
  tasks:
    - /bin/bash -lc '
        set -euo pipefail
        # <<< set your real deploy path here >>>
        DEPLOYPATH="/home/drrootsdc/public_html/betaroot"
        SOURCE="$PWD"
        LOG="/home/drrootsdc/deploy.log"

        {
          echo "===== FIX v4 $(date) ====="
          echo "SRC: $SOURCE"
          echo "DST: $DEPLOYPATH"

          # Create destination if missing with 755 perms (mkdir + chmod in one)
          /usr/bin/install -d -m 755 "$DEPLOYPATH"

          # Make sure current user can write inside (keeps outside world at 755)
          chmod u+rwX "$DEPLOYPATH"

          # Never keep a .git in destination
          [ -d "$DEPLOYPATH/.git" ] && rm -rf "$DEPLOYPATH/.git"

          # Prefer rsync if available, else tar fallback; always exclude .git & .cpanel.yml
          RSYNC="$(command -v rsync || true)"
          if [ -n "$RSYNC" ]; then
            echo "Using rsync: $RSYNC"
            "$RSYNC" -a --delete \
              --exclude ".git" --exclude ".cpanel.yml" \
              "$SOURCE"/ "$DEPLOYPATH"/
          else
            echo "rsync not found; using tar fallback"
            find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
            ( cd "$SOURCE" && tar --exclude=.git --exclude=.cpanel.yml -cf - . ) | ( cd "$DEPLOYPATH" && tar -xf - )
          fi

          echo "Done: $(date)"
        } >> "$LOG" 2>&1
      '
