---
deployment:
  tasks:
    # log a unique marker so we know THIS file ran
    - /bin/echo "===== DIAG v1 $(/bin/date) =====" >> /home/drrootsdc/deploy.log

    # show where cPanel is executing from and what's there
    - /bin/pwd >> /home/drrootsdc/deploy.log
    - /bin/ls -la >> /home/drrootsdc/deploy.log

    # ensure target exists
    - /bin/mkdir -p /home/drrootsdc/betaroot

    # try rsync, if it fails fall back to cp -a (and log stderr)
    - /usr/bin/rsync -av --delete --exclude ".git" --exclude ".cpanel.yml" ./ /home/drrootsdc/betaroot/ >> /home/drrootsdc/deploy.log 2>&1 || /bin/bash -lc 'echo "rsync failed or missing; using cp -a" >> /home/drrootsdc/deploy.log; cp -a ./.[!.]* ./..?* ./* /home/drrootsdc/betaroot/ 2>> /home/drrootsdc/deploy.log'
