---
deployment:
  tasks:
    - /bin/bash -lc '
        set -euo pipefail
        DEPLOYPATH="/home/drrootsdc/public_html/beta"  # <— set your real live path here
        SOURCE="$PWD"
        LOG="/home/drrootsdc/beta.log"

        {
          echo "===== FIX v3 $(date) ====="
          echo "SRC: $SOURCE"
          echo "DST: $DEPLOYPATH"

          # Ensure destination exists and is traversable/writable
          install -d -m 755 "$DEPLOYPATH"
          chmod -R u+rwX "$DEPLOYPATH" || true

          # Clean any stray .git in destination
          [ -d "$DEPLOYPATH/.git" ] && { echo "Removing stray .git"; rm -rf "$DEPLOYPATH/.git"; }

          # Detect rsync
          RSYNC="$(command -v rsync || true)"
          if [ -n "$RSYNC" ]; then
            echo "Using rsync: $RSYNC"
            "$RSYNC" -a --delete \
              --exclude ".git" --exclude ".cpanel.yml" \
              "$SOURCE"/ "$DEPLOYPATH"/
          else
            echo "rsync not found; using tar fallback"
            # If folder was recreated, it may be empty; delete-then-copy is still safe
            find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
            ( cd "$SOURCE" && tar --exclude=.git --exclude=.cpanel.yml -cf - . ) | ( cd "$DEPLOYPATH" && tar -xf - )
          fi

          echo "Done: $(date)"
        } >> "$LOG" 2>&1
      '
