---
deployment:
  tasks:
    - /bin/bash -lc '
        set -euo pipefail
        DEPLOYPATH="/home/drrootsdc/public_html/betaroot"   # <-- change if needed
        SOURCE="$PWD"
        LOG="/home/drrootsdc/deploy.log"

        {
          echo "===== SIMPLE cp DEPLOY $(date) ====="
          echo "SRC: $SOURCE"
          echo "DST: $DEPLOYPATH"

          # Create the destination folder if it doesn't exist
          mkdir -p "$DEPLOYPATH"
          chmod 755 "$DEPLOYPATH"

          # Remove any unwanted Git metadata before copying
          rm -rf "$DEPLOYPATH/.git" "$DEPLOYPATH/.cpanel.yml" 2>/dev/null || true

          # Copy everything recursively (-r), preserve attributes (-p),
          # and overwrite without prompt (-f)
          /bin/cp -prf "$SOURCE"/* "$DEPLOYPATH"/

          echo "Deployed with cp -prf to $DEPLOYPATH"
          echo "Done: $(date)"
        } >> "$LOG" 2>&1
      '
